//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ZIP Code&apos; field must contain exactly 8 numbers.
        /// </summary>
        public static string Account_CepFormat {
            get {
                return ResourceManager.GetString("Account_CepFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;ZIP Code&apos; field is required.
        /// </summary>
        public static string Account_CepRequired {
            get {
                return ResourceManager.GetString("Account_CepRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City cannot exceed 100 characters.
        /// </summary>
        public static string Account_CityMaxLength {
            get {
                return ResourceManager.GetString("Account_CityMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;City&apos; field is required.
        /// </summary>
        public static string Account_CityRequired {
            get {
                return ResourceManager.GetString("Account_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement cannot exceed 255 characters.
        /// </summary>
        public static string Account_ComplementMaxLength {
            get {
                return ResourceManager.GetString("Account_ComplementMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Confirm Password&apos; field is required.
        /// </summary>
        public static string Account_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Account_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF or CNPJ must be a valid number.
        /// </summary>
        public static string Account_CpfCnpjInvalid {
            get {
                return ResourceManager.GetString("Account_CpfCnpjInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the CPF field.
        /// </summary>
        public static string Account_CpfRequired {
            get {
                return ResourceManager.GetString("Account_CpfRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        public static string Account_CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Current Password&apos; field is required.
        /// </summary>
        public static string Account_CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("Account_CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth must be in the past.
        /// </summary>
        public static string Account_DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("Account_DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 100 characters.
        /// </summary>
        public static string Account_FullNameMaxLength {
            get {
                return ResourceManager.GetString("Account_FullNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide first and last name.
        /// </summary>
        public static string Account_FullNameMustIncludeFirstAndLastName {
            get {
                return ResourceManager.GetString("Account_FullNameMustIncludeFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the name field.
        /// </summary>
        public static string Account_FullNameRequired {
            get {
                return ResourceManager.GetString("Account_FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood cannot exceed 100 characters.
        /// </summary>
        public static string Account_NeighborhoodMaxLength {
            get {
                return ResourceManager.GetString("Account_NeighborhoodMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Neighborhood&apos; field is required.
        /// </summary>
        public static string Account_NeighborhoodRequired {
            get {
                return ResourceManager.GetString("Account_NeighborhoodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot exceed 100 characters.
        /// </summary>
        public static string Account_NewPasswordMaxLength {
            get {
                return ResourceManager.GetString("Account_NewPasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be at least 6 characters.
        /// </summary>
        public static string Account_NewPasswordMinLength {
            get {
                return ResourceManager.GetString("Account_NewPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from current password.
        /// </summary>
        public static string Account_NewPasswordMustBeDifferent {
            get {
                return ResourceManager.GetString("Account_NewPasswordMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;New Password&apos; field is required.
        /// </summary>
        public static string Account_NewPasswordRequired {
            get {
                return ResourceManager.GetString("Account_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Number&apos; field is required.
        /// </summary>
        public static string Account_NumberRequired {
            get {
                return ResourceManager.GetString("Account_NumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        public static string Account_PasswordChanged {
            get {
                return ResourceManager.GetString("Account_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation does not match new password.
        /// </summary>
        public static string Account_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Account_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must have 10 or 11 digits (area code + number).
        /// </summary>
        public static string Account_PhoneInvalid {
            get {
                return ResourceManager.GetString("Account_PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the phone field.
        /// </summary>
        public static string Account_PhoneRequired {
            get {
                return ResourceManager.GetString("Account_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must have 2 characters.
        /// </summary>
        public static string Account_StateLength {
            get {
                return ResourceManager.GetString("Account_StateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;State&apos; field is required.
        /// </summary>
        public static string Account_StateRequired {
            get {
                return ResourceManager.GetString("Account_StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street cannot exceed 255 characters.
        /// </summary>
        public static string Account_StreetMaxLength {
            get {
                return ResourceManager.GetString("Account_StreetMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Street&apos; field is required.
        /// </summary>
        public static string Account_StreetRequired {
            get {
                return ResourceManager.GetString("Account_StreetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string Account_UserNotFound {
            get {
                return ResourceManager.GetString("Account_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked. Please try again later.
        /// </summary>
        public static string Auth_AccountLocked {
            get {
                return ResourceManager.GetString("Auth_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication result is required.
        /// </summary>
        public static string Auth_AuthResultRequired {
            get {
                return ResourceManager.GetString("Auth_AuthResultRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Confirm Password&apos; field is required.
        /// </summary>
        public static string Auth_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Auth_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered on our platform. If you don&apos;t remember your password, use the Forgot Password tool.
        /// </summary>
        public static string Auth_EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("Auth_EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully.
        /// </summary>
        public static string Auth_EmailConfirmed {
            get {
                return ResourceManager.GetString("Auth_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string Auth_EmailInvalid {
            get {
                return ResourceManager.GetString("Auth_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed. Please check your inbox.
        /// </summary>
        public static string Auth_EmailNotConfirmed {
            get {
                return ResourceManager.GetString("Auth_EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email before logging in.
        /// </summary>
        public static string Auth_EmailNotConfirmedBeforeLogin {
            get {
                return ResourceManager.GetString("Auth_EmailNotConfirmedBeforeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email before recovering password.
        /// </summary>
        public static string Auth_EmailNotConfirmedBeforePasswordRecovery {
            get {
                return ResourceManager.GetString("Auth_EmailNotConfirmedBeforePasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; field is required.
        /// </summary>
        public static string Auth_EmailRequired {
            get {
                return ResourceManager.GetString("Auth_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate external user.
        /// </summary>
        public static string Auth_ExternalAuthFailed {
            get {
                return ResourceManager.GetString("Auth_ExternalAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get email from external provider.
        /// </summary>
        public static string Auth_ExternalProviderEmailNotFound {
            get {
                return ResourceManager.GetString("Auth_ExternalProviderEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password.
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Auth_InvalidData {
            get {
                return ResourceManager.GetString("Auth_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email confirmation.
        /// </summary>
        public static string Auth_InvalidEmailConfirmation {
            get {
                return ResourceManager.GetString("Auth_InvalidEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect.
        /// </summary>
        public static string Auth_InvalidPassword {
            get {
                return ResourceManager.GetString("Auth_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired token.
        /// </summary>
        public static string Auth_InvalidToken {
            get {
                return ResourceManager.GetString("Auth_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string Auth_LoginSuccessful {
            get {
                return ResourceManager.GetString("Auth_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be at least 6 characters.
        /// </summary>
        public static string Auth_NewPasswordMinLength {
            get {
                return ResourceManager.GetString("Auth_NewPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;New Password&apos; field is required.
        /// </summary>
        public static string Auth_NewPasswordRequired {
            get {
                return ResourceManager.GetString("Auth_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clean up old user.
        /// </summary>
        public static string Auth_OldUserCleanupFailed {
            get {
                return ResourceManager.GetString("Auth_OldUserCleanupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string Auth_PasswordChanged {
            get {
                return ResourceManager.GetString("Auth_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        public static string Auth_PasswordMinLength {
            get {
                return ResourceManager.GetString("Auth_PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery link sent to your email.
        /// </summary>
        public static string Auth_PasswordRecoveryLinkSent {
            get {
                return ResourceManager.GetString("Auth_PasswordRecoveryLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Password&apos; field is required.
        /// </summary>
        public static string Auth_PasswordRequired {
            get {
                return ResourceManager.GetString("Auth_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset instructions sent to your email.
        /// </summary>
        public static string Auth_PasswordResetSent {
            get {
                return ResourceManager.GetString("Auth_PasswordResetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully.
        /// </summary>
        public static string Auth_PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("Auth_PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string Auth_PasswordsMismatch {
            get {
                return ResourceManager.GetString("Auth_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider is required.
        /// </summary>
        public static string Auth_ProviderRequired {
            get {
                return ResourceManager.GetString("Auth_ProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token expired, invalid or revoked.
        /// </summary>
        public static string Auth_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Auth_RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string Auth_RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("Auth_RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required.
        /// </summary>
        public static string Auth_RefreshTokenRequired {
            get {
                return ResourceManager.GetString("Auth_RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please check your email to confirm your account.
        /// </summary>
        public static string Auth_RegistrationSuccessful {
            get {
                return ResourceManager.GetString("Auth_RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required.
        /// </summary>
        public static string Auth_TokenRequired {
            get {
                return ResourceManager.GetString("Auth_TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists.
        /// </summary>
        public static string Auth_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Auth_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UserId.
        /// </summary>
        public static string Auth_UserIdInvalid {
            get {
                return ResourceManager.GetString("Auth_UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId is required.
        /// </summary>
        public static string Auth_UserIdRequired {
            get {
                return ResourceManager.GetString("Auth_UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string Auth_UserNotFound {
            get {
                return ResourceManager.GetString("Auth_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet security requirements.
        /// </summary>
        public static string Auth_WeakPassword {
            get {
                return ResourceManager.GetString("Auth_WeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client created successfully.
        /// </summary>
        public static string Client_Created {
            get {
                return ResourceManager.GetString("Client_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client deleted successfully.
        /// </summary>
        public static string Client_Deleted {
            get {
                return ResourceManager.GetString("Client_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client with this email already exists.
        /// </summary>
        public static string Client_EmailDuplicate {
            get {
                return ResourceManager.GetString("Client_EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name is required.
        /// </summary>
        public static string Client_NameRequired {
            get {
                return ResourceManager.GetString("Client_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found.
        /// </summary>
        public static string Client_NotFound {
            get {
                return ResourceManager.GetString("Client_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client updated successfully.
        /// </summary>
        public static string Client_Updated {
            get {
                return ResourceManager.GetString("Client_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record created successfully.
        /// </summary>
        public static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error occurred.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record with this {0} already exists.
        /// </summary>
        public static string DuplicateEntry {
            get {
                return ResourceManager.GetString("DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Allowed formats: {0}.
        /// </summary>
        public static string File_InvalidFormat {
            get {
                return ResourceManager.GetString("File_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string File_NotFound {
            get {
                return ResourceManager.GetString("File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds maximum allowed size of {0}MB.
        /// </summary>
        public static string File_TooLarge {
            get {
                return ResourceManager.GetString("File_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        public static string File_UploadSuccessful {
            get {
                return ResourceManager.GetString("File_UploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access this resource.
        /// </summary>
        public static string ForbiddenAccess {
            get {
                return ResourceManager.GetString("ForbiddenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for {0}.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logged successfully.
        /// </summary>
        public static string LogError_Created {
            get {
                return ResourceManager.GetString("LogError_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating error log.
        /// </summary>
        public static string LogError_CreateError {
            get {
                return ResourceManager.GetString("LogError_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log deleted successfully.
        /// </summary>
        public static string LogError_Deleted {
            get {
                return ResourceManager.GetString("LogError_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting error log.
        /// </summary>
        public static string LogError_DeleteError {
            get {
                return ResourceManager.GetString("LogError_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the error.
        /// </summary>
        public static string LogError_ErrorRequired {
            get {
                return ResourceManager.GetString("LogError_ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the error log ID.
        /// </summary>
        public static string LogError_IdRequired {
            get {
                return ResourceManager.GetString("LogError_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log not found.
        /// </summary>
        public static string LogError_NotFound {
            get {
                return ResourceManager.GetString("LogError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log updated successfully.
        /// </summary>
        public static string LogError_Updated {
            get {
                return ResourceManager.GetString("LogError_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating error log.
        /// </summary>
        public static string LogError_UpdateError {
            get {
                return ResourceManager.GetString("LogError_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string MustBeLessThan {
            get {
                return ResourceManager.GetString("MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than 0.
        /// </summary>
        public static string Pagination_InvalidPageNumber {
            get {
                return ResourceManager.GetString("Pagination_InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be between 1 and 100.
        /// </summary>
        public static string Pagination_InvalidPageSize {
            get {
                return ResourceManager.GetString("Pagination_InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string Pagination_NoResults {
            get {
                return ResourceManager.GetString("Pagination_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status activated.
        /// </summary>
        public static string Status_Activated {
            get {
                return ResourceManager.GetString("Status_Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status created successfully.
        /// </summary>
        public static string Status_Created {
            get {
                return ResourceManager.GetString("Status_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating status.
        /// </summary>
        public static string Status_CreateError {
            get {
                return ResourceManager.GetString("Status_CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status deactivated.
        /// </summary>
        public static string Status_Deactivated {
            get {
                return ResourceManager.GetString("Status_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status deleted successfully.
        /// </summary>
        public static string Status_Deleted {
            get {
                return ResourceManager.GetString("Status_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting status.
        /// </summary>
        public static string Status_DeleteError {
            get {
                return ResourceManager.GetString("Status_DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot exceed 500 characters.
        /// </summary>
        public static string Status_DescriptionMaxLength {
            get {
                return ResourceManager.GetString("Status_DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string Status_IdRequired {
            get {
                return ResourceManager.GetString("Status_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete status because it is in use.
        /// </summary>
        public static string Status_InUse {
            get {
                return ResourceManager.GetString("Status_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A status with this name already exists.
        /// </summary>
        public static string Status_NameDuplicate {
            get {
                return ResourceManager.GetString("Status_NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 200 characters.
        /// </summary>
        public static string Status_NameMaxLength {
            get {
                return ResourceManager.GetString("Status_NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string Status_NameRequired {
            get {
                return ResourceManager.GetString("Status_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status not found.
        /// </summary>
        public static string Status_NotFound {
            get {
                return ResourceManager.GetString("Status_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope cannot exceed 100 characters.
        /// </summary>
        public static string Status_ScopeMaxLength {
            get {
                return ResourceManager.GetString("Status_ScopeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope is required.
        /// </summary>
        public static string Status_ScopeRequired {
            get {
                return ResourceManager.GetString("Status_ScopeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updated successfully.
        /// </summary>
        public static string Status_Updated {
            get {
                return ResourceManager.GetString("Status_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating status.
        /// </summary>
        public static string Status_UpdateError {
            get {
                return ResourceManager.GetString("Status_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha token is required.
        /// </summary>
        public static string Turnstile_TokenRequired {
            get {
                return ResourceManager.GetString("Turnstile_TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha validation failed. Please try again.
        /// </summary>
        public static string Turnstile_ValidationFailed {
            get {
                return ResourceManager.GetString("Turnstile_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
