namespace UI.API.Middleware
{
    /// <summary>
    /// Middleware to extract or generate a correlation ID for each HTTP request.
    /// The correlation ID is used to track requests across the entire application stack.
    /// Uses logging scopes to automatically add CorrelationId to all log entries.
    /// </summary>
    public class CorrelationIdMiddleware
    {
        private const string CorrelationIdHeader = "X-Correlation-ID";
        private readonly RequestDelegate _next;
        private readonly ILogger<CorrelationIdMiddleware> _logger;

        public CorrelationIdMiddleware(RequestDelegate next, ILogger<CorrelationIdMiddleware> logger)
        {
            _next = next;
            _logger = logger;
        }

        public async Task InvokeAsync(HttpContext context)
        {
            // Try to get correlation ID from request header
            var correlationId = context.Request.Headers[CorrelationIdHeader].FirstOrDefault();

            // If not present, fall back to TraceIdentifier (generated by ASP.NET Core)
            if (string.IsNullOrEmpty(correlationId))
                correlationId = context.TraceIdentifier;

            // Add correlation ID to response headers for client visibility
            context.Response.Headers[CorrelationIdHeader] = correlationId;

            // Add correlation ID to logging scope - this automatically adds it to ALL logs in this request
            using (_logger.BeginScope(new Dictionary<string, object>
            {
                ["CorrelationId"] = correlationId
            }))
            {
                // Continue processing the request
                await _next(context);
            }
        }
    }
}